version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=production
    networks:
      - frontend-network
    restart: unless-stopped

networks:
  frontend-network:
    driver: bridge